server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liuxiaojia1997/tensquare-config1.git
  rabbitmq:
    host: 192.168.25.133
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh